config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#main'

  scope '/admin' do
    resources :offers do
      get 'update-status', to: 'offers#status'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  # Validations
  validates :advertiser_name, :url, :description, :starts_at, presence: true
  validates :advertiser_name, uniqueness: true
  validates :url, format: URI::regexp(%w[http https])
  validates :description, length: { maximum: 500 }
  # Scopes
  scope :display_filter, -> { where(disabled_by_admin: false).order(premium: :desc) }

  def current_status
    return 'disabled by admin' if disabled_by_admin
    is_status_enabled? ? 'enabled' : 'disabled'
  end

  def is_status_enabled?
    return DateTime.now.between?(starts_at, ends_at) unless ends_at.nil?
    starts_at <= DateTime.now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  def index
    @offers = Offer.all
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)

    if @offer.save
      redirect_to offers_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @offer.update(offer_params)
      redirect_to offers_path
    else
      render 'edit'
    end
  end

  def destroy
    @offer.destroy

    redirect_to offers_path
  end

  def status
    offer = Offer.find(update_status_params[:offer_id])
    offer.update_attributes(disabled_by_admin: !offer.disabled_by_admin)
    redirect_to offers_path
  end

  private

  def offer_params
    params.require(:offer).permit(:advertiser_name, :url, :description, :starts_at, :ends_at, :premium)
  end

  def update_status_params
    params.permit(:offer_id)
  end

  def set_offer
    @offer = Offer.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
    @offers = Offer.display_filter.select do |offer|
      offer.current_status == 'enabled'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
  def reverse_status(status)
    # Still need to fix when disabled by admin
    if status == 'enabled'
      'disable'
    else
      'enable'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cashbacker</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/offers/_form.html.erb
<%= simple_form_for @offer do |form| %>
  <% if @offer.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2>
        <%= pluralize(@offer.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @offer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.input :advertiser_name, class: "form-control" %>

  <%= form.input :url, class: "form-control" %>

  <%= form.input :description, class: "form-control" %>

  <%= form.input :starts_at, order: [:day, :month, :year] %>

  <%= form.input :ends_at, include_blank: true, order: [:day, :month, :year] %>

  <%= form.input :premium, class: "form-check-input" %>

  <%= form.button :submit, class: 'btn btn-primary' %>

  <%= link_to 'Back', offers_path, class: 'btn btn-secondary' %>

<% end %>

app/views/offers/edit.html.erb
<h1>Edit Offer</h1>

<%= render 'form' %>

app/views/offers/index.html.erb
<h1>Listing Offers</h1>
<%= link_to 'New Offer', new_offer_path %>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>id</th>
      <th>name</th>
      <th>url</th>
      <th>status</th>
      <th colspan="3">actions</th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.id %></td>
        <td><%= offer.advertiser_name %></td>
        <td><%= offer.url %></td>
        <td><%= offer.current_status %></td>
        <td><%= link_to '[edit]', edit_offer_path(offer) %></td>
        <td><%= link_to "[#{reverse_status(offer.current_status)}]", offer_update_status_path(offer.id) %></td>
        <td><%= link_to '[destroy]', offer_path(offer), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form' %>

app/views/pages/_listing.html.erb
<div class="row row-cols-1 row-cols-md-2">
  <% @offers.each do |offer| %>
    <div class="col mb-4">
      <div class="card h-100">
        <h5 class="card-header">
          <%= offer.advertiser_name %>
          <% if offer.premium %>
            <span class="badge badge-pill badge-info">Premium</span>
          <% end %>
        </h5>
        <div class="card-body">
          <p class="card-text">
            <%= offer.description %>
          </p>
          <%= link_to "Shop Now", offer.url, target: "_blank", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/main.html.erb
<h1>Available Offers</h1>

<%= render 'listing' %>